Repository GongGanGam/GongGanGam-iOS, pull requests merged in 2023-01, with the labels that each got.

#59 feat: fastlane 설정 추가
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: 🔧 Configuration

#62 TitledSegmentedControl 구현
  GongGanGam-UI/Sources/Example/TitledViewExampleViewController.swift
  GongGanGam-UI/Sources/TitledView/TitledSegmentedControl.swift
  GongGanGam-UI/Sources/TitledView/TitledSegmentedControlDelegate+DataSource.swift
Labels: 💄 Style

#63 AlertBuilder 구현
  GongGanGam-UI/Sources/AlertBuilder/AlertBuilder.swift
  GongGanGam-UI/Sources/AlertBuilder/AlertBuilderExampleViewController.swift
  GongGanGam-UI/Sources/Example/Components.swift
Labels: 💄 Style

#64 SelectionView
  GongGanGam-UI/Resources/Asset.xcassets/Emoji_Disabled/curious_disabled.imageset/Contents.json
  GongGanGam-UI/Resources/Asset.xcassets/Emoji_Disabled/curious_disabled.imageset/curios_disabled.png
  GongGanGam-UI/Resources/Asset.xcassets/Emoji_Disabled/curious_disabled.imageset/curios_disabled@2x.png
  GongGanGam-UI/Resources/Asset.xcassets/Emoji_Disabled/curious_disabled.imageset/curios_disabled@3x.png
  GongGanGam-UI/Sources/Example/Components.swift
  GongGanGam-UI/Sources/SelectionView/SelectionView.swift
  GongGanGam-UI/Sources/SelectionView/SelectionViewDelegate+DataSource.swift
  GongGanGam-UI/Sources/SelectionView/SelectionViewExampleViewController.swift
  GongGanGam-UI/Sources/SelectionView/SelectionViewItem.swift
Labels: 💄 Style

#65 feat: create CheckBox
  GongGanGam-UI/Sources/CheckBox/CheckBox.swift
  GongGanGam-UI/Sources/CheckBox/CheckBoxExampleViewController.swift
  GongGanGam-UI/Sources/Example/Components.swift
Labels: 💄 Style

#66 GongGanGamButton 구현
  GongGanGam-UI/Sources/Example/Components.swift
  GongGanGam-UI/Sources/GongGanGamButton/GongGanGamButton.swift
  GongGanGam-UI/Sources/GongGanGamButton/GongGanGamButtonExampleViewController.swift
Labels: 💄 Style

#68 ProfileImageView
  GongGanGam-UI/Resources/Asset.xcassets/Color/Shadow.colorset/Contents.json
  GongGanGam-UI/Sources/Example/Components.swift
  GongGanGam-UI/Sources/ProfileImageView/ProfileImageView.swift
  GongGanGam-UI/Sources/ProfileImageView/ProfileImageViewExampleViewController.swift
  GongGanGam-UI/Sources/ProfileImageView/ShadowProfileImageView.swift
Labels: 💄 Style

#69 feat: create ReceivedContentCell
  GongGanGam-UI/Sources/Example/Components.swift
  GongGanGam-UI/Sources/ReceivedContent/ReceivedContentCell.swift
  GongGanGam-UI/Sources/ReceivedContent/ReceivedContentCellExampleViewController.swift
Labels: 💄 Style

#70 ChatPreviewCell
  GongGanGam-UI/Sources/ChatPreviewCell/ChatPreviewCell.swift
  GongGanGam-UI/Sources/ChatPreviewCell/ChatPreviewCellExampleViewController.swift
  GongGanGam-UI/Sources/Example/Components.swift
Labels: 💄 Style

#72 hotfix: xcdatamodel 파일 변경사항 적용
  Project.swift
Labels: bug
